CREATE TABLE OrderBookSpanshots (
    id INT(64) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	order_id VARCHAR(36) NOT NULL,
	price VARCHAR(32) NOT NULL,
	sequence VARCHAR(32) NOT NULL,
	side VARCHAR(4) NOT NULL,
	size VARCHAR(32) NOT NULL
)